### REST Client extension for visual code
### Get All notes
GET http://localhost:3000/notes HTTP/1.1
content-type: application/json

### Get one note by id
GET http://localhost:3000/notes/5aa5ccbbe38c7421283baaf0 HTTP/1.1
content-type: application/json

### Create a note
POST http://localhost:3000/notes HTTP/1.1
content-type: application/json

{
  "title": "Goku here",
  "content": "Transforming into a super saiyan"
}
### Update a note by id
PUT http://localhost:3000/notes/5aa5ccbbe38c7421283baaf0 HTTP/1.1
content-type: application/json

{
  "title": "Goku SSJ",
  "content": "KA-MEEEE-HAAAAA-MEEEEEEEE..... HAAAAAA!!!!!!!"
}
### Delete a note by id
DELETE http://localhost:3000/notes/5aa5ccbbe38c7421283baaf0 HTTP/1.1
content-type: application/json