### REST Client extension for visual code
### Get All quotes
GET http://localhost:3000/api/quotes HTTP/1.1
content-type: application/json

### Get one quote by id
GET http://localhost:3000/api/quotes/5aa6cb59cf3612432401a138 HTTP/1.1
content-type: application/json

### Create a quote
POST http://localhost:3000/api/quotes HTTP/1.1
content-type: application/json

{
  "hero": "Goku",
  "message": "Transforming into a super saiyan"  
}

### Update a quote by id
PUT http://localhost:3000/api/quotes/5aa6cb59cf3612432401a138 HTTP/1.1
content-type: application/json

{
  "hero": "Goku SSJ",
  "message": "KA-MEEEE-HAAAAA-MEEEEEEEE..... HAAAAAA!!!!!!!"
}
### Delete a quote by id
DELETE http://localhost:3000/api/quotes/5aa6cb59cf3612432401a138 HTTP/1.1
content-type: application/json